version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-elitebpong
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge